### ISSUE TITLE
'target' dir gets more filled after each build

### ISSUE THREAD

**Issue by dizzzz** [claudius108/kuberam-expath-plugin#10]
During each build an other "expath-descripters-*" directory is generated, with an unique identifier:

![testartifact____development_github_testartifact__-_____xar-assembly_xml__testartifact_](https://user-images.githubusercontent.com/1700062/34652621-29070a2a-f3e1-11e7-9354-b8975ad506c8.jpg)

It is probable better (...) to remove this unique identifier and have this directory cleaned at each run?

**Comment by claudius108** [comment]
Do you use ”mvn clean package” for building?

**Comment by dizzzz** [comment]
hmmm no, you  have a point there. I should do that.
But why is this 'uuid like pattern' there?

**Comment by claudius108** [comment]
Honestly, I do not remember this right now. I think it was exactly for cases when building without the clean phase.

Anyway, I removed it.
