### ISSUE TITLE
Use of github releases

### ISSUE THREAD

**Issue by dizzzz** [claudius108/kuberam-expath-plugin#11]
Please consider tagging releases in github ; it requires only a few clicks:

step 1:
![capture1](https://user-images.githubusercontent.com/1700062/34774410-81496d56-f60f-11e7-8d72-3dcb3d21e7dd.PNG)

step 2
![capture2](https://user-images.githubusercontent.com/1700062/34774412-82f7e876-f60f-11e7-9dce-c6d33fdb0ddb.PNG)

and a step 3....

rationale: tracing of current and old versions

**Comment by claudius108** [comment]
Started to use releases, thanks.
