### ISSUE TITLE
repo.xml permissions element : only set attributes when data is available

### ISSUE THREAD

**Issue by dizzzz** [claudius108/kuberam-expath-plugin#12]
see https://github.com/claudius108/kuberam-expath-plugin/blob/c2ee7698a8de55e646f58f770ba510abfe3ccef7/src/main/resources/ro/kuberam/maven/plugins/expath/generate-descriptors.xsl#L135 

As a result `@password` is always to "", which is not good. Suggestion: only add `user/password/group/mode` when a value is actually set

@adamretter this is rather critical for the jms/replication extension
@claudius108 how are your xslt skills?

```xslt
<xsl:if test="/*/pkg:permissions">
  <xsl:variable name="permissions" select="/*/pkg:permissions" />
  <permissions user="{$permissions/@user}" password="{$permissions/@password}"
                   group="{$permissions/@group}" mode="{$permissions/@mode}" />
</xsl:if>
```

**Comment by dizzzz** [comment]
can we use a `<xsl:copy-of select=/*/pkg:permissions/node()"/>` or so? or is the namespace the problem? or what about copying attributes only? `<xsl:copy-of select="/*/pkg:permissions/@*" />` or so?

**Comment by claudius108** [comment]
I will look at it tomorrow.

**Comment by claudius108** [comment]
I will look at it tomorrow.

**Comment by dizzzz** [comment]
I'll contact @adamretter  ...

**Comment by claudius108** [comment]
Release v. 0.5.5, which fixed this.

**Comment by dizzzz** [comment]
thnx! I found an issue under windows, I filed another issue for this....

**Comment by claudius108** [comment]
Can we close this?
