### ISSUE TITLE
xar-assembly puts wrong namespace on changelog

### ISSUE THREAD

**Issue by duncdrum** [claudius108/kuberam-expath-plugin#17]
### What is the problem
The default xar builder thinks that the exist-db specific `repo.xml` elements `changelog` and `change` are in the expath namespace, they are not they should be in `xmlns="http://exist-db.org/xquery/repo"` namespace

### Workaround
Its easy to workaround this by specifying manually. But a fix at the source would be nice, should be similarly easy to fix. 

### Reproduce
see https://github.com/eXist-db/public-repo/issues/50 for examples and listings. Simply create a changeling in xar-assembly and observe that the elements are copied into `target/expath-decsriptors/repo.xml` but with the wrong namespace.

**Comment by claudius108** [comment]
Thanks for pointing this.
I released v. 0.6.3, which fixes this. Just wait for few hours for it.
