### ISSUE TITLE
Unable to register XQuery libraries in expath-pkg.xml

### ISSUE THREAD

**Issue by adamretter** [claudius108/kuberam-expath-plugin#2]
We use the Maven `kuberam-expath-plugin` to create the XAR package for the https://github.com/eXist-db/xquery-versioning-module, however that does not seem to provide any option for adding xquery components to the generated `expath-pkg.xml` which is created in the XAR file.

For example our `expath-pkg.xml` which is generated currently looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://expath.org/ns/pkg" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    name="http://exist-db.org/xquery/versioning" abbrev="xquery-versioning-module"
    version="1.2-SNAPSHOT" spec="1.0">
    <title>Versioning Module</title>
    <home>https://www.github.com/exist-db/xquery-versioning-module</home>
    <dependency processor="http://exist-db.org" semver-min="3.0.4"/>
</package>
```

However, for eXist (and inline with the EXPath spec) to know that the `verisoning.xqm` module is available in the EXPath package, our `expath-pkg.xml` would need to look like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://expath.org/ns/pkg" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    name="http://exist-db.org/xquery/versioning" abbrev="xquery-versioning-module"
    version="1.2-SNAPSHOT" spec="1.0">
    <title>Versioning Module</title>
    <home>https://www.github.com/exist-db/xquery-versioning-module</home>
    <dependency processor="http://exist-db.org" semver-min="3.0.4"/>
    <xquery>
        <namespace>http://exist-db.org/versioning</namespace>
        <file>versioning.xqm</file>
    </xquery>
</package>
```

There does not seem to be away to add that configuration to the descriptor for the plugins configuration. You can see our configuration here: https://github.com/eXist-db/xquery-versioning-module/blob/master/pom.xml#L172 and the descriptor that we use for the plugin here: https://github.com/eXist-db/xquery-versioning-module/blob/master/xar-assembly.xml

**Comment by claudius108** [comment]
Hi,

Version 0.4.9 fixes this. Use:

    <xquerySets>
        <xquerySet>
        	<namespace>http://exist-db.org/versioning</namespace>
            <directory>${basedir}/src/main/xquery</directory>
            <includes>
                <include>versioning.xqm</include>
            </includes>
            <outputDirectory>content</outputDirectory>
        </xquerySet>
    </xquerySets>

**Comment by adamretter** [comment]
@claudius108 Fantastic :-) Thank you, that seems to have fixed it.

**Comment by claudius108** [comment]
You are all welcome, as you all deserve the better! :)
