### ISSUE TITLE
resource elements inside components.xml

### ISSUE THREAD

**Issue by duncdrum** [claudius108/kuberam-expath-plugin#5]
Hi Claudius, 

the plugin currently creates a separate `components.xml` which lists resources. I can't quite figure out where this is coming from, since `expath-pkg.xml` can contain these, eg. via `<xquery>`, `<rng>`, `<resource>`, … 

Would it be possible to drop this file, and include its contents in `expath-pkg.xml` instead? This would make it easier for expath apps in eXist. @adamretter said he would be willing to help, but we would like to understand the `compoments.xml` first.             
  
see eXist-db/exist-apps-archetype#2

**Comment by claudius108** [comment]
Hi,

The file components.xml lists all the resources that are of interest for expath-pkg.xml or exist.xml.

Why is this file bothering you? It is not considered by the EXPath Package processors?

**Comment by duncdrum** [comment]
No it isn't and I can't find any references in the specs that say that it should. 
`exist.xml` is fine as it is.

**Comment by claudius108** [comment]
I will remove it.

**Comment by adamretter** [comment]
@claudius108 It's more that the content of `components.xml` needs to be placed in the `expath-pkg.xml` in a slightly different format.

**Comment by claudius108** [comment]
Fixed in v. 0.5.2, which I just deployed in maven central repo. Please wait for it around 2 hours.
