### ISSUE TITLE
Allow multiple java modules in exist.xml

### ISSUE THREAD

**Issue by dizzzz** [claudius108/kuberam-expath-plugin#7]
See https://github.com/eXist-db/exist-apps-archetype/issues/4 

according to 'the spec' the following is allowed in `exist.xml` but is not (yet) supported by the plugin:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://exist-db.org/ns/expath-pkg">
    <jar>exist-mongrel-@VERSION@.jar</jar>
    <jar>mongodb-driver-3.4.2.jar</jar>
    <jar>mongodb-driver-core-3.4.2.jar</jar>
    <jar>bson-3.4.2.jar</jar>
    <java>
        <namespace>http://expath.org/ns/mongo</namespace>
        <class>org.exist.mongodb.xquery.MongodbModule</class>
    </java>
    <java>
        <namespace>http://expath.org/ns/mongo/gridfs</namespace>
        <class>org.exist.mongodb.xquery.GridfsModule</class>
    </java>
</package>
```

**Comment by claudius108** [comment]
Fixed in version 0.5.3, which I am now trying to release.

The syntax is as follows:
<package>
        ...
	<components>
		<resource>
			<public-uri>http://expath.org/ns/mongo</public-uri>
			<file>org.exist.mongodb.xquery.MongodbModule</file>
		</resource>
		<resource>
			<public-uri>http://expath.org/ns/mongo/gridfs</public-uri>
			<file>org.exist.mongodb.xquery.GridfsModule</file>
		</resource>
	</components>
</package>

**Comment by dizzzz** [comment]
```xml
<package> 
    ... 
    <components>
        <resource>
            <public-uri>http://expath.org/ns/mongo</public-uri>
            <file>org.exist.mongodb.xquery.MongodbModule</file>
        </resource>
        <resource>
            <public-uri>http://expath.org/ns/mongo/gridfs</public-uri>
            <file>org.exist.mongodb.xquery.GridfsModule</file>
        </resource>
    </components>
</package>
```

**Comment by claudius108** [comment]
Hm, how?

**Comment by claudius108** [comment]
No, how did you wrote indented XML?

The above syntax I mentioned is EXPath Package-like. I will change the other syntaxes, too, in the future, to be EXPath Package-like.

**Comment by dizzzz** [comment]
ahhhhh, ok. 
![allow_multiple_java_modules_in_exist_xml_ _issue__7_ _claudius108_kuberam-expath-plugin](https://user-images.githubusercontent.com/1700062/34741000-84b3ff12-f581-11e7-9436-fcd40a6a0c68.jpg)

**Comment by claudius108** [comment]
Great, thanks.

So, I jujst released version 0.5.4, which should fix this.

**Comment by dizzzz** [comment]
fyi..... below the the text box is a manual I see right now: https://guides.github.com/features/mastering-markdown/

**Comment by claudius108** [comment]
Thanks a lot.
